### ISSUE TITLE
Multiplication gates, and proof generation time

### ISSUE THREAD

**Issue by FCW2018** [Charterhouse/pysnark#2]
Hi
I'm working academic paper and I have written a prototype that utilizes Pysnark. I would like to ask if it is possible to determine some values such as the number of multiplication gates, and proof generation time

**Comment by meilof** [comment]
Cool!

PySNARK does not directly give you the number of multiplication gates, but it does give the "length" of the quadratic arithmetic program underlying the computation, i.e., the number of equations it consists of. This is actually the most relevant performance parameter since this is what proof generation time mostly scales in. In the example below it is 93 equations. Also relevant is the "size", here 128, which is basically the number of equations rounded up to the nearest power of two. 

If you really need the number of multiplications, what you could do is a word count on the equations file:

meilof$ wc pysnark_eqs_main 
      93    1180   11138 pysnark_eqs_main

Here, the equation file has 93 lines and 1180 tokens. Since each line has 3 fixed tokens and then two tokens per multiplication, the number of multiplications is around (1180−3×93)/2 = 450. (I see now there is a small bug in PySNARK that makes this slightly inaccurate, let me know if you need the exact number.)

For timing, I would directly run qapprove and just clock its execution time, e.g., "time ../qaptools/qapprove pysnark_masterek pysnark_wires pysnark_values pysnark_schedule" 

Hope that helps!

```
examples meilof$ python testarray.py 
array [3, 4, 5, 6] 5 {5}
array [3, 4, 1, 6] 1 {1}
matrix [[1, 2], [3, 4], [5, 6]]
matrix get row [[1, 2], [3, 4], [5, 6]] [3, 4] [{3}, {4}]
matrix get el [[{1}, {2}], [{3}, {99}], [0, {8}]] {99}
   main main 300e1cc83b5de4dd 93 *
qaplen: 93 blklen: 0 extlen: None sz 128 pubsz 0
Reading QAP from (pysnark_eqs_main,pysnark_ek_main)
Proving main (pysnark_ek_main)
Compute h 1
Reading QAP vk: pysnark_vk_main
Verifying main (pysnark_vk_main) 1
Verification succeeded
  prover keys/eqs:  pysnark_masterek pysnark_ek_main pysnark_eqs_main pysnark_schedule
  prover data:      
  verifier keys:    pysnark_masterpk pysnark_vk_main pysnark_schedule
  verifier data:     pysnark_proof pysnark_values
  verifier cmd:     /Library/Python/2.7/site-packages/pysnark/qaptools/qapver pysnark_masterpk pysnark_schedule pysnark_proof pysnark_values
```

**Comment by FCW2018** [comment]
Thank you for your valuable response. I'm also wondering if it is possible to implement hash pre-image proof. For example, the prover knows a secret value x such that y=sha256(x).

**Comment by meilof** [comment]
Yes, support for the GGH hash function is built-in, see the examples
included.
